// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd7zzTkgGXxWGYy1D28v7Dxv5sQU78xKc',
    appId: '1:952009399537:web:a469145ac54385cf8b1d50',
    messagingSenderId: '952009399537',
    projectId: 'lab10-24df0',
    authDomain: 'lab10-24df0.firebaseapp.com',
    storageBucket: 'lab10-24df0.firebasestorage.app',
    measurementId: 'G-FVGJC0LECW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC85E55jyvnnngp-tlspHQhuvhTcmXNTB0',
    appId: '1:952009399537:android:071b0aaf4ca853b98b1d50',
    messagingSenderId: '952009399537',
    projectId: 'lab10-24df0',
    storageBucket: 'lab10-24df0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKbak_A9ERJldi3VD68oazm7NaiiDrXZk',
    appId: '1:952009399537:ios:6afc1042194df6378b1d50',
    messagingSenderId: '952009399537',
    projectId: 'lab10-24df0',
    storageBucket: 'lab10-24df0.firebasestorage.app',
    iosBundleId: 'com.example.lab10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKbak_A9ERJldi3VD68oazm7NaiiDrXZk',
    appId: '1:952009399537:ios:6afc1042194df6378b1d50',
    messagingSenderId: '952009399537',
    projectId: 'lab10-24df0',
    storageBucket: 'lab10-24df0.firebasestorage.app',
    iosBundleId: 'com.example.lab10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd7zzTkgGXxWGYy1D28v7Dxv5sQU78xKc',
    appId: '1:952009399537:web:30916026b439a2ab8b1d50',
    messagingSenderId: '952009399537',
    projectId: 'lab10-24df0',
    authDomain: 'lab10-24df0.firebaseapp.com',
    storageBucket: 'lab10-24df0.firebasestorage.app',
    measurementId: 'G-DPC0T000NF',
  );
}
